---


- name: Install EPEL Repository
#  yum: name="http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm" state=present
  yum: name="epel-release" state=present
  become: True
  tags:
   - install
   - repository


- name: Install Redis using yum
  yum: name=redis state=present
  become: True
  tags:
    - redis
    - installation
    - install
    - yum


- name: Serve to other machines
  replace: dest=/etc/redis.conf regexp="^bind 127.0.0.1$" replace="bind 0.0.0.0"
  become: True
  tags:
    - redis
    - configuration
    - file


- name: Avoid storing anything in disk to reduce latency
  replace: dest=/etc/redis.conf regexp="^{{ item }}$" replace="#{{ item }}"
  with_items:
    - "save 900 1"
    - "save 300 10"
    - "save 60 10000"
  become: True
  tags:
    - redis
    - configuration
    - file


- name: Start Redis upon reboot
  shell: systemctl enable redis
  become: True
  notify: restart redis
  tags:
    - enable
    - redis
