---


# Needed at least the first time after creating vagrant machine.
# Calling this role once is enough, so allow_duplicates should be defined as "no" (it's the default behaviour).

- name: Update packages
  sudo: True
  apt: update_cache=yes
  when: ansible_os_family == "Debian"
  environment: proxy_env
  tags:
    - apt
    - update
    - debian