---

- name: Configure proxies in Git
  shell: "git config --global {{ item.var_name }} {{ item.proxy_value }}"
  when: item.proxy_value
  with_items:
    - { var_name: 'http.proxy', proxy_value: '{{ proxy_env.http_proxy }}' }
    - { var_name: 'https.proxy', proxy_value: '{{ proxy_env.https_proxy }}' }
  tags:
    - configure
    - proxy
    - git


- name: Set proxies as environment variables
  lineinfile:
    dest: .bashrc
    regexp: 'export {{ item.var_name }}'
    line: 'export {{ item.var_name }}={{ item.proxy_value }}'
    state: present
    backup: yes
  when: item.proxy_value
  with_items:
    - { var_name: 'http_proxy', proxy_value: '{{ proxy_env.http_proxy }}' }
    - { var_name: 'https_proxy', proxy_value: '{{ proxy_env.https_proxy }}' }
    - { var_name: 'ftp_proxy', proxy_value: '{{ proxy_env.ftp_proxy }}' }
  tags:
    - configure
    - proxy
    - environment
