---

- name: Install Gunicorn
  pip: name={{ item }} virtualenv="{{ venv_path }}"
  with_items:
    - gunicorn
    - greenlet
    - gevent
  tags:
    - install
    - gunicorn


- name: Copy configuration file to run unicorn with our app
  template: src=gunicorn_config.py.j2 dest="{{ gunicorn_config }}"
  tags:
   - copy
   - configuration
   - api
