---

- name: Install supervisor
  yum: name=supervisor state=present
  become: True
  # when: ansible_os_family == "RedHat"
  tags:
    - install
    - supervisor
    - yum


- name: Copy supervisor config file to run unicorn with our app
  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf
  become: True
  tags:
   - copy
   - configuration
   - supervisor


- name: Create folders needed for logs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  become: True
  with_items:
    - "{{ celery_log_folder }}"
    - "{{ gunicorn_log_folder }}"
  tags:
   - create
   - folder
   - log


- name: Start supervisor upon reboot
  shell: systemctl enable supervisord
  become: True
  notify:
    - restart supervisor
  tags:
    - enable
    - supervisor
