---


# In Ubuntu Trusty this is necessary to access to i386 packages.
- name: Enable access to i386 architecture's packages
  sudo: True
  command: "dpkg --add-architecture i386"
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - dpkg
    - architecture
    - i386


# Needed at least the first time after creating vagrant machine.
# WARNING: this is redundant. An apt-update has already been done in dependent "docker" role.
# Would it be best to create a role to ensure that it is called just once?
# (cons: create a new role only for this?)
- name: Update packages
  sudo: True
  apt: update_cache=yes
  when: ansible_os_family == "Debian"
  environment: proxy_env
  tags:
    - apt
    - update
    - debian


- name: Bulk dependency installation
  sudo: True
  apt:
    pkg: "{{ item }}"
    state: present
  when: ansible_os_family == "Debian"
  environment: proxy_env
  with_items:
    - "libgtk2.0-0:i386"
    - "libnss3-1d:i386"
    - "libnspr4-0d:i386"
    - "lib32nss-mdns"
    - "libxml2:i386"
    - "libxslt1.1:i386"
    - "libqtwebkit-dev:i386"
    - "libssl-dev:i386"
  tags:
    - apt
    - installation
    - install
    - dependency
    - debian
