FROM  {{ docker_base_image }}
MAINTAINER "Aitor Gomez-Goiri" <aitor.gomez-goiri@open.ac.uk>


# Install vnc and xvfb (and xfce) in order to create a graphic session
RUN   apt-get update && apt-get install -y \
      x11vnc \
      xvfb
{%- if install_xfce %} \
      xfce4 \
      xfce4-goodies
{% endif %}


# Clean packages
RUN   apt-get autoclean && apt-get autoremove && rm -rf /var/lib/apt/lists/*


# Configure VNC server
RUN   mkdir ~/.vnc && x11vnc -storepasswd "{{ vnc_password }}" ~/.vnc/passwd


# Set tasks to run in the appropriate order (Xvfb, x11vnc and PT)
COPY  supervisord.conf /etc/supervisor/conf.d/supervisord.conf


EXPOSE {{ docker_vnc_port }}
EXPOSE {{ docker_pt_port }}


#ENTRYPOINT
CMD   ["/usr/bin/supervisord"]
