FROM  {{ docker_base_image }}
MAINTAINER "Aitor Gomez-Goiri" <aitor.gomez-goiri@open.ac.uk>


# Install vnc and xvfb (and xfce) in order to create a graphic session
RUN   apt-get update && apt-get install -y \
      xvfb
{%- if install_vnc %} \
      x11vnc
{% endif %}
{%- if install_xfce %} \
      xfce4 \
      xfce4-goodies
{% endif %}


# Clean packages
RUN   apt-get autoclean && apt-get autoremove && rm -rf /var/lib/apt/lists/*


{% if install_vnc %}
# Configure VNC server
RUN   mkdir ~/.vnc && x11vnc -storepasswd "{{ vnc_password }}" ~/.vnc/passwd


# Set tasks to run in the appropriate order
COPY  supervisord.conf /etc/supervisor/conf.d/supervisord.conf


CMD   ["/usr/bin/supervisord"]
{% else %}
COPY  packettracer.sh /usr/bin/packettracer
# Supervisor is actually unneeded, but it is still provided because
#   (a) it doesn't add too much overhead to the image and
#   (b) it offers an additional supervised way to run Packet Tracer if needed.
COPY  supervisord.conf /etc/supervisor/conf.d/supervisord.conf


CMD   ["/usr/bin/packettracer"]
{% endif %}
