FROM  {{ base_image }}
MAINTAINER "Aitor Gomez-Goiri" <aitor.gomez-goiri@open.ac.uk>


# Copy and configure PacketTracer
# FIXME optional files and folders can not exist so ADD could fail
{% for file in compressed_installation_file.files %}
{%  if file.optional %}
{%    set src = docker_context_installation_subfolder + "/" + file.backup %}
{%    set dest = file.original_path + "/" + file.original_name %}
ADD   {{ src }} {{ dest }}
{%  endif %}
{% endfor %}
# Not copying PT installation folder
{% for folder in compressed_installation_file.folders %}
{%  if folder.optional %}
{%    set src = docker_context_installation_subfolder + "/" + folder.backup %}
{%    set dest = folder.original %}
ADD   {{ src }} {{ dest }}
{%  endif %}
{% endfor %}


# Note: If any build steps change the data within the volume after
# it has been declared, those changes will be discarded.
VOLUME
{%- for folder in compressed_installation_file.folders %}
{%    if not folder.optional %}
 {{ folder.original }}
{%    endif %}
{%- endfor %}
