FROM  {{ docker_base_image }}
MAINTAINER "Aitor Gomez-Goiri" <aitor.gomez-goiri@open.ac.uk>


ENV   DEBIAN_FRONTEND noninteractive

# FIXME keyboard layout selection (28)
RUN   apt-get update && apt-get install -y \
      tightvncserver \
      apt-utils \
      xfce4 \
      xfce4-goodies \
      expect


# Clean packages
RUN   apt-get autoclean && apt-get autoremove && rm -rf /var/lib/apt/lists/*


# Configure VNC server
RUN   touch /root/.ICEauthority && mkdir /root/.vnc
COPY  xstartup /root/.vnc/xstartup
COPY  vncpasswd.sh /root/vncpasswd.sh
RUN   chmod ug+x /root/vncpasswd.sh && /root/vncpasswd.sh "{{ vnc_password }}"


# Copy and configure PacketTracer
ADD   {{ compressed_installation_file.name }} {{ compressed_installation_file.decompressed }}
{% for file in compressed_installation_file.files %}
{%    set src = compressed_installation_file.decompressed + "/" + file.backup %}
{%    set dest = file.original_path + "/" + file.original_name %}
{%    if file.optional %}
RUN   if [ -f "{{ src }}" ]; then mv {{ src }} {{ dest }}; fi
{%    else %}
RUN   mv {{ src }} {{ dest }}
{%    endif %}
{% endfor %}
{% for folder in compressed_installation_file.folders %}
{%    set src = compressed_installation_file.decompressed + "/" + folder.backup %}
{%    set dest = folder.original %}
{%    if folder.optional %}
RUN   if [ -d "{{ src }}" ]; then mv {{ src }} {{ dest }}; fi
{%    else %}
RUN   mv {{ src }} {{ dest }}
{%    endif %}
{% endfor %}


# Set tasks to run in the appropriate order (VNC, Xfce and PT)
COPY  supervisord.conf /etc/supervisor/conf.d/supervisord.conf


EXPOSE {{ docker_vnc_port }}
EXPOSE {{ docker_pt_port }}


#ENTRYPOINT
CMD   ["/usr/bin/supervisord"]
