---

- name: Install nginx
  yum: name=nginx state=present
  become: True
  # when: ansible_os_family == "RedHat"
  tags:
    - install
    - nginx
    - yum


- name: Create directories for config files
  file: path="{{item}}" state=directory
  become: True
  with_items:
    - /etc/nginx/sites-available
  tags:
    - create
    - config
    - directory
    - nginx


- name: Copy nginx config file for our app
  copy: src=flaskapp.conf dest=/etc/nginx/sites-available/flaskapp.conf
  become: True
  tags:
    - copy
    - config
    - nginx


- name: Create symbolic link to enable the config file of our app
  file: src=/etc/nginx/sites-available/flaskapp dest=/etc/nginx/conf.d/flaskapp.conf state=link
  become: True
  notify:
    - restart nginx
  tags:
    - link
    - config
    - nginx