---

- include_vars: vars.secret.yml
- name: Build base image with VNC
  include: build_image.yml
  vars:
    context_path: "{{ xvfb_base_context }}"
    image_name: "{{ docker_xvfb_base_image }}"
    install_vnc: True
    pt_command: "{{installation_path}}/bin/PacketTracer6 saves/FORGE/ibookdemo611.pkt"


# Mounted always as the data-only container will be of this type
- name: Build docker container with Packet Tracer embedded
  include: pt_add.yml


- name: Build GUIless image
  include: build_image.yml
  vars:
    context_path: "{{ nogui_base_context }}"
    image_name: "{{ docker_nogui_image }}"
    install_vnc: False
    pt_command: "{{installation_path}}/bin/PacketTracer6 --no-gui --ipc-port {{ docker_pt_port }} saves/FORGE/ibookdemo611.pkt"


- name: Prepare folders to be mounted in the Packet Tracer container
  include: pt_mount.yml
  vars:
    context_path: "{{ xvfb_ptmount_context }}"
    image_name: "{{ docker_xvfb_ptmount_image }}"
    base_image: "{{ docker_nogui_image }}"
  when: not include_pt


- name: Reminders for docker usage
  debug: msg="{{ item }}"
  with_items:
   - "docker images"
   - "docker inspect {{ docker_image }}"
   - "docker rmi {{ docker_image }}"
   - "docker ps  ( running containers )"
   - "docker ps -a  ( all containers )"
   - "docker start/stop/rm container_id"
   - "docker rm $(docker ps -a -q)"
   - "docker port container_id"
