---

- include_vars: vars.secret.yml
- name: Update and copy Dockerfile for PT
  template:
    src: "Dockerfile_base.j2"
    dest: "./Dockerfile_xvfb"
  tags:
   - template
   - copy
   - files
   - docker


- name: Copy installation file
  copy: src="{{ installation_file }}" dest="./"
  tags:
   - copy
   - files
   - docker


- name: Copy supervisor's configuration file
  template:
    src: "supervisord.conf.j2"
    dest: "./supervisord.conf"
  tags:
   - copy
   - files
   - docker


# Problem that I have not been able to solve:
#   https://github.com/ansible/ansible-modules-core/issues/921
- name: Build docker container automatically
  shell: "docker build --rm -t {{ docker_xvfb_base_image }} -f Dockerfile_xvfb ./"
  ignore_errors: True
  register: container_build
  tags:
   - build
   - container
   - docker


- name: Build docker container manually
  when: container_build.rc == 1
  debug: msg="docker build --rm -t {{ docker_xvfb_base_image }} -f Dockerfile_xvfb ./"


- name: Prepare folders to be mounted in the Packet Tracer container
  include: pt_mount.yml
  when: not include_pt


- name: Build docker container with Packet Tracer embedded
  include: pt_add.yml
  when: include_pt


- name: Reminders for docker usage
  debug: msg="{{ item }}"
  with_items:
   - "docker images"
   - "docker inspect {{ docker_image }}"
   - "docker rmi {{ docker_image }}"
   - "docker ps  ( running containers )"
   - "docker ps -a  ( all containers )"
   - "docker start/stop/rm container_id"
   - "docker rm $(docker ps -a -q)"
   - "docker port container_id"
