---

- name: Build base image
  include: build_base_image.yml
  vars:
    context_path: "{{ xvfb_base_context }}"
    image_name: "{{ docker_xvfb_base_image }}"


# Mounted always as the data-only container will be of this type
- name: Create a data volume container which contains Packet Tracer
  include: create_data_container.yml


- name: Build image without Packet Tracer installation (it should be mounted later on)
  include: build_final_image.yml
  vars:
    context_path: "{{ xvfb_ptmount_context }}"
    image_name: "{{ docker_xvfb_ptmount_image }}"
    base_image: "{{ docker_xvfb_base_image }}"
  when: not include_pt


- name: Reminders for docker usage
  debug: msg="{{ item }}"
  with_items:
   - "docker images"
   - "docker inspect {{ docker_image }}"
   - "docker rmi {{ docker_image }}"
   - "docker ps  ( running containers )"
   - "docker ps -a  ( all containers )"
   - "docker start/stop/rm container_id"
   - "docker rm $(docker ps -a -q)"
   - "docker port container_id"
