---

- name: Update and copy Dockerfile for adding PT
  template:
    src: "Dockerfile_include_pt.j2"
    dest: "./Dockerfile_xvfb_include"
  tags:
   - template
   - copy
   - files
   - docker


- name: Build docker container automatically
  shell: "docker build --rm -t {{ docker_image_pt_included }} -f Dockerfile_xvfb_include ./"
  ignore_errors: True
  register: container_build
  tags:
   - build
   - container
   - docker


- name: Build docker container manually
  when: container_build.rc == 1
  debug: msg="docker build --rm -t {{ docker_image_pt_included }} -f Dockerfile_include ./"


- name: Reminder to run image built
  debug: msg="docker run -p 5901:{{ docker_vnc_port }}  -p  39000:{{ docker_pt_port }} -ti {{ docker_image_pt_included }}"
