---

- name: Create xvfb_mount context and PT uncompressing folder
  file: path="{{ docker_context_uncompressed_installation }}" state=directory


- name: Update and copy Dockerfile for adding PT
  template:
    src: "Dockerfile_mount_pt.j2"
    dest: "{{ xvfb_ptmount_context }}/Dockerfile"
  tags:
   - template
   - copy
   - files
   - docker


- name: Uncompress installation files
  shell: "tar zxvf {{ xvfb_ptadd_context }}/{{ compressed_installation_file.name }} -C {{ docker_context_uncompressed_installation }}"
#  unarchive:
#    src: "{{ compressed_installation_file.name }}"
#    dest: "{{ compressed_installation_file.decompressed }}"
#    creates: yes
#    copy: no
  tags:
   - uncompress
   - installation
   - files
   - packetTracer


- name: Remove unused PT main folder (it will be mounted from a data-only container)
  shell: "{{ item }}"
  become: True
  with_items:
    - "rm -rf {{ docker_context_uncompressed_installation }}/{{ compressed_installation_file.folders[0].backup }}"


- name: Build docker container automatically
  shell: "docker build --rm -t {{ docker_xvfb_ptmount_image }} {{ xvfb_ptmount_context }}"
  ignore_errors: True
  register: container_build
  tags:
   - build
   - container
   - docker


- name: Add 'packettracer' tag
  shell: "docker tag  -f {{ docker_xvfb_ptmount_image }} {{ docker_image }}"
  when: container_build.rc != 1
  ignore_errors: True
  register: container_build
  tags:
   - container
   - docker
   - tag


- name: Build docker container manually
  debug: msg="{{ item }}"
  when: container_build.rc == 1
  with_items:
    - "docker build --rm -t {{ docker_xvfb_ptmount_image }} {{ xvfb_ptmount_context }}"
    - "docker tag {{ docker_xvfb_ptmount_image }} {{ docker_image }}"


- name: Remove temporary folder
  file: path="{{ compressed_installation_file.decompressed }}" state=absent


- name: Reminder to run image built
  debug: msg="docker run --volumes-from {{ data_container }} -p 5901:{{ docker_vnc_port }} -p 39000:{{ docker_pt_port }} -ti {{ docker_image }}"
  when: not include_pt
