---

- name: Update and copy Dockerfile for adding PT
  template:
    src: "Dockerfile_mount_pt.j2"
    dest: "./Dockerfile_xvfb_mount"
  tags:
   - template
   - copy
   - files
   - docker


- name: Build docker container automatically
  shell: "docker build --rm -t {{ docker_xvfb_ptmount_image }} -f Dockerfile_xvfb_mount ./"
  ignore_errors: True
  register: container_build
  tags:
   - build
   - container
   - docker


- name: Add 'packettracer' tag
  shell: "docker tag {{ docker_xvfb_ptmount_image }} {{ docker_image }}"
  when: container_build.rc != 1
  ignore_errors: True
  register: container_build
  tags:
   - container
   - docker
   - tag


- name: Build docker container manually
  debug: msg="{{ item }}"
  when: container_build.rc == 1
  with_items:
    - "docker build --rm -t {{ docker_xvfb_ptmount_image }} -f Dockerfile_xvfb_mount ./"
    - "docker tag {{ docker_xvfb_ptmount_image }} {{ docker_image }}"


- name: Create temporary folder
  file: path="{{ compressed_installation_file.decompressed }}" state=directory


- name: Uncompress installation files
  shell: "tar zxvf {{ compressed_installation_file.name }} -C {{ compressed_installation_file.decompressed }}"
#  unarchive:
#    src: "{{ compressed_installation_file.name }}"
#    dest: "{{ compressed_installation_file.decompressed }}"
#    creates: yes
#    copy: no
  tags:
   - uncompress
   - installation
   - files
   - packetTracer


- name: Move installation folder to appropriate path
  shell: "mv {{ compressed_installation_file.decompressed }}/{{ compressed_installation_file.folders[0].backup }} {{ compressed_installation_file.folders[0].original }}"
  become: True


- name: Change ownership of the installation folder
  file:
    path: "{{ compressed_installation_file.folders[0].original }}"
    owner: "{{ remote_user }}"
    group: "{{ remote_group }}"
  become: True


- name: Remove temporary folder
  file: path="{{ compressed_installation_file.decompressed }}" state=absent


- name: Reminder to run image built
  debug: msg="docker run -p 5901:{{ docker_vnc_port }}  -p  39000:{{ docker_pt_port }} -ti {{ docker_image }} -v {{ compressed_installation_file.folders[0].original }}:{{ compressed_installation_file.folders[0].original }}"
