---

- include_vars: vars.secret.yml


- name: "Create {{ xfce_context }} context"
  file: path="{{ xfce_context }}" state=directory


- name: Update and copy Dockerfile
  template:
    src: "Dockerfile.j2"
    dest: "{{ xfce_context }}/Dockerfile"
  tags:
   - template
   - copy
   - files
   - docker


- name: Copy secondary files
  copy: src="{{ item }}" dest="{{ xfce_context }}"
  with_items:
    - "xstartup"
    - "vncpasswd.sh"
  tags:
   - copy
   - files
   - docker


- name: Copy installation file
  copy:
    src: "{{ installation_file }}"
    dest: "{{ xfce_context }}/{{ compressed_installation_file.name }}"
  tags:
   - copy
   - files
   - docker


- name: Copy supervisor's configuration file
  template:
    src: "supervisord.conf.j2"
    dest: "{{ xfce_context }}/supervisord.conf"
  tags:
   - copy
   - files
   - docker


# Problem that I have not been able to solve:
#   https://github.com/ansible/ansible-modules-core/issues/921
- name: Build docker container automatically
  shell: "docker build --rm -t {{ docker_image }} {{ xfce_context }}"
  ignore_errors: True
  register: container_build
  tags:
   - build
   - container
   - docker


- name: Build docker container manually
  when: container_build.rc == 1
  debug: msg="docker build --rm -t {{ docker_image }} {{ xfce_context }}"


- name: Reminders for docker usage
  debug: msg="{{ item }}"
  with_items:
   - "docker images"
   - "docker inspect {{ docker_image }}"
   - "docker rmi {{ docker_image }}"
   - "docker run -p 5901:{{ docker_vnc_port }}  -p  39000:{{ docker_pt_port }} -ti {{ docker_image }}"
   - "docker ps  ( running containers )"
   - "docker ps -a  ( all containers )"
   - "docker start/stop/rm container_id"
   - "docker rm $(docker ps -a -q)"
   - "docker port container_id"
