---

# file: main.yml


- name: Check if VNC passwd file exists
  stat: path="{{home_dir}}/.vnc/passwd"
  register: passfile
  tags:
    - passwd
    - file
    - existence


- include: install.yml
- include: create_passfile.yml
  # It creates the passwd file only if it does not exist yet.
  when: not passfile.stat.exists 
- include: configure_init.yml