---

# Install Docker in CentOS 7

- name: Update CentOS
  yum: name=* state=latest
  become: True
  tags:
   - update
   - centos


- name: Install Docker Repository
  yum: name="https://get.docker.com/rpm/1.7.0/centos-7/RPMS/x86_64/docker-engine-1.7.0-1.el7.centos.x86_64.rpm" state=present
  become: True
  tags:
   - install
   - repository
   - docker

# Change data directory in CentOS 7:
#   sudo nano /usr/lib/systemd/system/docker.service
#      Append ""-g /data/docker" at the end of "ExecStart" line.
#   sudo systemctl daemon-reload
#   sudo service docker restart
#   sudo ps -ax | grep "docker"
# (NOTE: editing /etc/sysconfig/docker did not seem to have an effect)


- name: Add current user to docker group
  user: name="{{ remote_user }}" groups="docker" append=yes
  become: True
  register: added_to_group
  tags:
   - add
   - group
   - docker


- name: Start the docker daemon at boot
  shell: chkconfig docker on
  become: True
  tags:
   - start
   - daemon
   - boot
   - docker


- include: proxy.yml
  become: True


- name: restart docker
  shell: service docker restart
  become: True
  tags:
    - docker
    - restart
