---

# Warning: WebSockets do not work in the current tomcat7 repositories
#  (install "tomcat7-examples" and go to /examples/websocket/echo.xhtml to check it)
- name: Install tomcat7 using apt
  sudo: True
  apt:
    pkg: "{{ item }}"
    state: present
  when: ansible_os_family == "Debian"
  environment: proxy_env
  with_items:
    - "tomcat7"
    - "tomcat7-admin"
  tags:
    - apt
    - installation
    - install
    - dependency
    - debian

