---

# Warning: WebSockets do not work in the current tomcat7 repositories
#  (install "tomcat7-examples" and go to /examples/websocket/echo.xhtml to check it)


- name: Install Tomcat using yum
  yum: name="{{ item }}" state=present
  with_items:
    - "tomcat"
    - "tomcat-admin-webapps"
  tags:
    - tomcat7
    - installation
    - install
    - yum

- include_vars: vars.secret.yml
- name: Set Tomcat configuration
  template:
    src: tomcat-users.xml.j2
    dest: "{{ tomcat7_yum_path }}/tomcat-users.xml"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0744
  tags:
    - configuration
    - tomcat7


- name: Start Tomcat upon reboot
  shell: systemctl enable tomcat
  notify: restart tomcat7-yum
  tags:
    - enable
    - tomcat7
