---


# In Ubuntu Trusty this is necessary to access to i386 packages.
- name: Enable access to i386 architecture's packages
  sudo: True
  command: "dpkg --add-architecture i386"
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - dpkg
    - architecture
    - i386


- name: Bulk dependency installation
  sudo: True
  apt:
    pkg: "{{ item }}"
    state: present
  when: ansible_os_family == "Debian"
  environment: proxy_env
  with_items:
    - "libgtk2.0-0:i386"
    - "libnss3-1d:i386"
    - "libnspr4-0d:i386"
    - "lib32nss-mdns"
    - "libxml2:i386"
    - "libxslt1.1:i386"
    - "libqtwebkit-dev:i386"
    - "libssl-dev:i386"
  tags:
    - apt
    - installation
    - install
    - dependency
    - debian
