---

- name: Check if folder existed
  stat: path="{{ installation_path }}"
  register: instp
  tags:
    - folder
    - packettracer
    - existence


- name: Create PT folder
  file:
    path: "{{ installation_path }}"
    state: directory
    owner: vagrant
  when: not instp.stat.exists
  tags:
    - folder
    - create
    - packettracer
    - installation


- name: Copy PT data
  copy:
    src:  "{{ original_path }}"
    dest: "{{ installation_path }}"
    owner: vagrant
    group: vagrant
  when: not instp.stat.exists
  tags:
    - packettracer
    - installation
    - install
    - copy


- name: Ensure that is executable
  file:
    src:  "{{ original_path }}"
    dest: "{{ installation_path }}/{{ pt_bin_relative_path }}"
    mode: "u=rwx,g=rx,o=r"
    state: file
  tags:
    - packettracer
    - installation
    - install
    - chmod
    - permissions
    - executable
