---

- name: Check if folder exists
  stat: path="{{ installation_path }}"
  register: instp
  tags:
    - folder
    - packettracer
    - existence


- name: Create PT folder
  file:
    path: "{{ installation_path }}"
    state: directory
    owner: vagrant
  when: not instp.stat.exists
  tags:
    - folder
    - create
    - packettracer
    - installation


- name: Copy PT data
  unarchive:
    src:  "{{ original_path }}"
    dest: "{{ installation_path }}"
    owner: vagrant
    group: vagrant
  when: not instp.stat.exists
  tags:
    - packettracer
    - installation
    - install
    - copy
    - unpack


- name: Ensure that is executable
  file:
    dest: "{{ item }}"
    mode: "u=rwx,g=rx,o=r"
    state: file
  with_items:
    - "{{ installation_path }}/{{ pt_bin_relative_path }}"
    - "{{ installation_path }}/set_ptenv.sh"
    - "{{ installation_path }}/extensions/upnp/upnp"  # Otherwise it will prompt an error message on start...
  tags:
    - packettracer
    - installation
    - install
    - chmod
    - permissions
    - executable


- name: Ensure that the user owns the profile folder
  sudo: True
  file:
    dest: "/etc/profile"
    owner: "{{remote_user}}"
    group: "{{remote_user}}"
