---

- name: Create PT folder
  file:
    path: "{{ installation_path }}"
    state: directory
    owner: vagrant
  tags:
    - user
    - folder
    - packettracer


# vncserver :0
- name: Copy PT data
  copy:
    src:  "{{ original_path }}"
    dest: "{{ installation_path }}"
    owner: vagrant
    group: vagrant
  tags:
    - packettracer
    - installation
    - install
    - copy
