---

- name: Copy weblab daemon configuration file
  copy: src="{{upstart_file}}" dest="{{daemon_conf_file}}" # owner=foo group=foo mode=0644
  sudo: True
  tags:
    - upstart
    - daemon
    - copy
    - configuration
    - packetTracer


- name: Replace variables in upstart task (the user which executes it, the path to the PacketTracer instance and the log file)
  replace: dest="{{daemon_conf_file}}" regexp="\[\[{{item.name}}\]\]" replace="{{item.value}}" # backup=yes
  with_items:
    - { name: 'execuser', value: '{{remote_user}}' }
    - { name: 'pt_exec', value: '{{ pt_path }}/{{ pt_bin_relative_path }}' }
    - { name: 'log_file', value: '{{ upstart_log }}' }
    - { name: 'display_number', value: '{{ x_display }}' }
  sudo: True
  tags:
    - upstart
    - daemon
    - replace
    - configuration
    - packetTracer
    - instance


- name: Create log file if it does not exist
  file: path="{{upstart_log}}" state="touch" owner="{{remote_user}}"
  sudo: True
  tags:
    - upstart
    - daemon
    - log
    - file
    - create
    - configuration
    - packetTracer
    - instance



# TODO Consider using Systemd
# Apparently, even Ubuntu plans to stop using Upstream
- name: Reload configuration for daemons
  shell: "initctl reload-configuration"
  sudo: True
  tags:
    - initctl
    - reload
    - configuration
    - daemon